[project]
name = "kalshi-trading-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=44.0.0",
    "dotenv>=0.9.9",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]
